### ISSUE TITLE
Publish on nuget.org

### ISSUE THREAD

**Issue by WenceyWang** [falox/libvirt-csharp#1]
It's time to target net5.0 and I think you can publish the package to nuget.org?

**Comment by falox** [comment]
The supported API functions are still few, networking and storage support completely missing. @WenceyWang what's your use case? Which functions are you using most? Feel free to submit a PR, we can try to implement a minimum set of functions and then release the first version.

**Comment by WenceyWang** [comment]
I am writing a daemon to create and dispose VM for CI.

I am preparing a PR for now.

**Comment by falox** [comment]
@WenceyWang so the current functions are already enough for you?

**Comment by WenceyWang** [comment]
I think I need network API and I am working on it.

**Comment by falox** [comment]
In the meantime, I've released the nuget at https://www.nuget.org/packages/libvirt-csharp

**Comment by falox** [comment]
@WenceyWang I've released a nuget with your changes https://www.nuget.org/packages/libvirt-csharp/0.0.1-alpha2
